server:
  port: 8080
spring:
  application:
    name: cloud-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@peer1:8761/eureka/
#zuul:
#  routes:
#    goods:
#      path: /goods/**
#      serviceId: cloud-goods
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
ribbon:
  ReadTimeout: 1000
  ConnectTimeout: 1000